<a href="https://colab.research.google.com/github/Hithashreee/PythonMLNLP/blob/main/mevi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DAY **1**

In [ ]:
print("Hello World")

Hello World


In [ ]:
print(ord('a'))
print(bin(97))


97
0b1100001


In [ ]:
name=input("enter your name")
print('hello')

enter your namehitha
hello


In [ ]:
import random
r=random.randint(0,100)
n1=input("enter your name ")
n2=input ("enter his or her name")
print('your love score is ',r,'%')

enter your name hitha
enter his or her namemanish
your love score is  93 %


In [ ]:
print('Ascii values->',ord('*'),ord ('P'),ord('V'),)
print(bin(18),bin(21),)

Ascii values-> 42 80 86
0b10010 0b10101


In [ ]:
#addiction
a=int(input('enter a'))
print(type(a))
b=int(input('enter b'))
print(type(b))
print(a+b)


enter a21
<class 'int'>
enter b18
<class 'int'>
39


In [ ]:
#string concate
a=input('enter a')
print(type(a))
b=input('enter b')
print(type(b))
print(a+b)

enter a21
<class 'str'>
enter b18
<class 'str'>
2118


In [ ]:
# DATA TYPES
#int
a=10
print(a,'Int')
#float
b=10.5
print(b,'float')
c='Hello'
print(c,'string')
b=True
print(a,'Boolean')
d='1+3j'

10 Int
10.5 float
Hello string
10 Boolean


In [ ]:
print('Ascii values ->', ord('*'),ord('M'),ord('E'),)

Ascii values -> 42 77 69


**DAY 2**

In [ ]:
a=int(input('enter a'))
print(type(a))
b=int(input('enter b'))
print(type(b))
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a**2)
print(b**2)

enter a32
<class 'int'>
enter b14
<class 'int'>
46
18
448
2
1024
196


In [ ]:
import math

In [ ]:
import math
c=math.sqrt(18)
c

4.242640687119285

In [ ]:
gcd=math.gcd(18,21)
gcd

3

In [ ]:
f=math.factorial(5)
f

120

In [ ]:
for i in range (1,11):
  print('inside',i)
  print('outside')

inside 1
outside
inside 2
outside
inside 3
outside
inside 4
outside
inside 5
outside
inside 6
outside
inside 7
outside
inside 8
outside
inside 9
outside
inside 10
outside


In [ ]:
for i in range (1,10,2):
  print(i)

1
3
5
7
9


In [ ]:
for i in range (3,31,3):
  print(i)

3
6
9
12
15
18
21
24
27
30


In [ ]:
i=int(input('enter a number'))
for i in range(i,i*10,i):
  print(i)

enter a number5
5
10
15
20
25
30
35
40
45


In [ ]:
i=int(input('enter a number'))
for i in range(a,a*10,a):
  print(a,'*',i//a,'=',i)

enter a number5
32 * 1 = 32
32 * 2 = 64
32 * 3 = 96
32 * 4 = 128
32 * 5 = 160
32 * 6 = 192
32 * 7 = 224
32 * 8 = 256
32 * 9 = 288


In [ ]:
age=int(input('enter the age'))
if(age>=60):
  print('can vote')
elif(age>=18):
  print('renew your card')
else:
  print('cant vote')

enter the age70
can vote


In [ ]:
n=0
while(n<=5):
  n=n+1
  print(n)

1
2
3
4
5
6


In [ ]:
n=0
while(n<=5):
  print(n)
  n=n+1

0
1
2
3
4
5


In [ ]:
print('welcome to union bank')
mpin=2118
n=0
while(n<=3):
  upin=int(input('enter your pin'))
  if(upin==mpin):
    print('successfully logged in')
    break
  elif(n==3):
    print('sorry account blocks')
  else:
     print('invalid pin try again')
  n=n+1 #n+=1

welcome to union bank
enter your pin1244
invalid pin try again
enter your pin2118
successfully logged in


In [ ]:
import random
number=random.randint(0,10)
while True:
  guess=int(input('guess a number'))
  if(number==guess):
    print('you won')
    break
  elif(guess<number):
    print('number guessed too low')
  elif(guess>number):
    print('number guessed too high')
  else:
    print('you lost')
    break

guess a number5
number guessed too low
guess a number9
number guessed too high
guess a number7
number guessed too high
guess a number8
number guessed too high
guess a number6
you won


**DAY 3:**

In [ ]:
# assignment operator
a=0

In [ ]:
a=3
a-=1 #a=a-1
print(a)

2


In [ ]:
a+=1 #a=a+1
a+=a #a=a+a
print(a)

46


In [ ]:
a=3
a*=a #a=a*a
print (a)

9


In [ ]:
print ('Welcome to ICICI Bank')
mpin='0606'
bal=25000
n=1
while(n<=3):
  upin=input ('Enter your pin')
  if(len(upin)==4):
    if(upin==mpin):
      print ('successfully logged in')
      s='''
      -Operations-
      1-Desposit
      2-Withdraw
      3-Checkbalance
      '''
      print(s)
      ch=int(input('enter your choice'))
      if(ch==1):
        amt=int(input('how much amount you want to deposit'))
        bal+=amt
        print(f'{amt} has been deposited and your balance is {bal}')
      elif(ch==2):
        amt=int(input('how much amount you want to withdraw'))
        bal-=amt
        print(f'{amt} has been withdrawn and your balance is {bal}')
      elif(ch==3):
        print(f'{amt}check your balance ={bal}')


      break
    elif(n==3):
      print('sorry account block')
    else:
      print('invalid pin')
  else:
    print('check the number of digits')
    n=n+1 #n+=1

Welcome to ICICI Bank
Enter your pin0606
successfully logged in

      -Operations-
      1-Desposit
      2-Withdraw
      3-Checkbalance
      
enter your choice3
10000check your balance =25000


In [ ]:
#itteration
name= "Hitha shree"
for i in name:
  print(i)


H
i
t
h
a
 
s
h
r
e
e


In [ ]:
name= "Hitha shree"
for i in name:
  print(i*10)


HHHHHHHHHH
iiiiiiiiii
tttttttttt
hhhhhhhhhh
aaaaaaaaaa
          
ssssssssss
hhhhhhhhhh
rrrrrrrrrr
eeeeeeeeee
eeeeeeeeee


In [ ]:
#string methods
s='Hey this Python Class'
print(s.upper())
print(s.lower())
print(s.title())
print(len(s))
print(s.find('e'))
print(s.startswith('Hey'))
print(s.endswith('ss'))
s=s.replace('Python','Python ML NLP')
print(s)

HEY THIS PYTHON CLASS
hey this python class
Hey This Python Class
21
1
True
True
Hey this Python ML NLP Class


In [ ]:
#string Slicing
s[0:21:3]

'H iPh a'

In [ ]:

s=input('enter the string')
print(s.upper())
print(s.lower())
print(s.title())
print(len(s))
print(s.find('e'))
print(s.startswith('Hey'))
print(s.endswith('ss'))
ss=input('enter the sub string')
rs=input('enter the new string')
s=s.replace(ss,rs)
print(s)

enter the stringhello this hitha
HELLO THIS HITHA
hello this hitha
Hello This Hitha
16
1
False
False
enter the sub stringhitha
enter the new stringvidya
hello this vidya


In [ ]:
s=input('enter the main string').lower()
l=input('which letter count you want').lower()
c=0
for i in s:
  if(i==l):
    c+=1
print(c)

enter the main stringHELLO hello
which letter count you wantl
4


In [ ]:
s=input('enter the main string').lower()
a=0
e=0
i=0
o=0
u=0
for j in s:
  if(j=='a'):
    a+=1
  elif(j=='e'):
    e+=1
  elif(j=='i'):
    i+=1
  elif(j=='o'):
    o+=1
  elif(j=='u'):
    u+=1
print('a->',a,'e->',e,'i->',i,'o->',o,'u->',u)


enter the main stringhelloooo
a-> 0 e-> 1 i-> 0 o-> 4 u-> 0


In [ ]:
'1'.isnumeric()

True

In [ ]:
'a'.isalpha()

True

In [ ]:
' '.isspace()

True

In [ ]:
s=input('enter the main string').lower()
a=0
for j in s:
  if(j.isalpha()=='a'):
    print(j)
  elif(j.isspace()=='a'):
    print(j)
  elif(j.isnumeric()=='a'):
    print (j)

enter the main stringhelloo 123


**DAY 4**

In [ ]:
#Data structures(INBUILT)
#List
#Set
#dictionary


In [ ]:
#List Properties
#Ordered
#indexed
#heterogenous
#mutable

In [ ]:
a=[1,2,3,4,5,6,7,8,'hello']
a


[1, 2, 3, 4, 5, 6, 7, 8, 'hello']

In [ ]:
a[1]=21 #change
a

[1, 21, 3, 4, 5, 6, 7, 8, 'hello']

In [ ]:
a.append('hitha') #add
a

[1, 21, 3, 4, 5, 6, 7, 8, 'hello', 'hitha']

In [ ]:
a.remove('hello')
a

[1, 21, 3, 4, 5, 6, 7, 8, 'hitha']

In [ ]:
t=(1,2,3,4,5,6,7,8,'hello')
t

(1, 2, 3, 4, 5, 6, 7, 8, 'hello')

In [ ]:
def reverse_array(arr):
  return arr[::-1]
arr=[1,2,3,4,5]
print(reverse_array(arr))

[5, 4, 3, 2, 1]


In [ ]:
#arthematic operations
number=[1,2,3,4,5,6]
find_largest=max(number)
find_smallest=min(number)
find_smallest , find_largest


(1, 6)

In [ ]:
w=[1,2,3,4,5,6,7,8,9]
gs=[ 3,4,6,7]
extra=[]
for i in w:
  if (i in gs):
    pass
  else:
    extra.append(i)
print(extra)

[1, 2, 5, 8, 9]


In [ ]:
w=['7259959939','9353576773',
9880852178,
7892094882,
9380011766,
6364684957,
9449945527,
9353037876,
9148327607,
9886678142,
8073659755,
8884065958,
8123302663,
9110879058,
9353926345,
8147424676,
9611775982,
6363129192,
9353457325,
6366266576,
6363505511,
9113662972,
8618093520,
8861145572,
6362810066,
7760706020,
8317409682,
8105723936,
9019647750,
9483672274,
9743597412,
9482840301,
9480741723,
7676667422,
9945904019,
8660654024,
9912130104,
6364841177,
6366474714,
7892652772,
8105138442,
8217400359,
8310788250,
8431499433,
9019024387,
9019439392,
9663473286]
gs=[ 7259959939,
9353576773,
9880852178,
7892094882,
9380011766,
6364684957,
9449945527,
9353037876,
9148327607,
9886678142,
8073659755,
8884065958,
8123302663,
9110879058,
9353926345,
8147424676,
9611775982,
6363129192,
9353457325,
6366266576,
6363505511,
9113662972,
8618093520,
8861145572,
6362810066,
7760706020
]
extra=[]
for i in w:
  if (i in gs):
    pass
  else:
    extra.append(i)
print(extra)

['7259959939', '9353576773', 8317409682, 8105723936, 9019647750, 9483672274, 9743597412, 9482840301, 9480741723, 7676667422, 9945904019, 8660654024, 9912130104, 6364841177, 6366474714, 7892652772, 8105138442, 8217400359, 8310788250, 8431499433, 9019024387, 9019439392, 9663473286]


In [ ]:
l=[1,2,3,4,5,7,8,56,23,1,2,4,5,7,7,56]
print(min(l))
print(max(l))
print(sum(l))
print(sum(l)//len(l)) #float operation

1
56
191
11


In [ ]:
l.index(5)

4

In [ ]:
l.insert(5,6)
l

[1, 2, 3, 4, 5, 6, 6, 6, 7, 8, 56, 23, 1, 2, 4, 5, 7, 7, 56]

In [ ]:
l.pop()

56

In [ ]:
l.count(7)

3

In [ ]:
l=sorted(l)
l

[1, 1, 2, 2, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7, 8, 23, 56]

In [ ]:
import random
l=['rock','paper','scissor']
r=random.choice(l)

while True:
  start=input('start game:')
  print(r)
  if(r==start):
     print('you lost')
  else:
    print('you won')
    break



start game:paper
rock
you won


In [ ]:
#assignment
import random
l=['rock','paper','scissor']
r=random.choice(l)
while True:
  start=input('enter your choice:')
  print(r)
  if(r==start):
     print('its a tie')
  else:
    print('you gain 1 point')
  break

In [ ]:
n=True
while(n):
  ans=input('Please give me your phone').lower()
  if(ans=='yes'):
    print('thank you so much you are so sweet')
    n=False #break
  else:
    print('please please please')

Please give me your phoneno
please please please
Please give me your phoneo
please please please
Please give me your phoneyes
thank you so much you are so sweet


In [ ]:
 bill=0
while(True):
  menu='''
  1-idly -20Rs
  2-dosa - 50Rs
  3-Puri - 40Rs
  '''
  print(menu)
  ch=int(input('Enter your choice'))
  q=int(input('Enter the main meal quantity'))
  if(ch==1):
    bill+=20*q
  elif(ch==2):
    bill+=50*q
  j='''
  1-orange-40
  2-apple-40
  3-fanta-30
  '''
  ju=int(input('Enter juice'))
  if(ju==1):
    bill+=40

  exit=input('do you want to exit')
  if(exit=='yes'):
    print('thank you your total bill is',bill,'rs')
    break


 1-idly -20Rs
 2-dosa - 50Rs
 3-Puri - 40Rs
 
Enter your choice1
Enter the main meal quantity3
Enter juice2
do you want to exitno

 1-idly -20Rs
 2-dosa - 50Rs
 3-Puri - 40Rs
 
Enter your choice2
Enter the main meal quantity3
Enter juice2
do you want to exityes
thank you your total bill is 210 rs



features of dictionaries


*   heterogenous
*   unordered
*   key indexed
*   mutable
*   does not allow duplicate keys



In [ ]:
d={
    "name":"hitha",
    "id":1234,
 "name":"manish"
}
d

{'name': 'manish', 'id': 1234}

In [ ]:
d.items()

dict_items([('name', 'manish'), ('id', 1234)])

In [ ]:
d.values()

dict_values(['manish', 1234])

In [ ]:
d.keys()

dict_keys(['name', 'id'])

In [ ]:
d1={
    "name":"vidya",
    "id":1235,
}
d1

{'name': 'vidya', 'id': 1235}

In [ ]:
d2={
    "name":"pranitha",
    "id":1236,
}
d2

{'name': 'pranitha', 'id': 1236}

In [ ]:
l=[d,d1,d2]
print('Employee Details')
print('------------------')
for k in l:
  for i,j in k.items():
    print(i,'-->',j)
  print('--------------')

Employee Details
------------------
name --> manish
id --> 1234
--------------
name --> vidya
id --> 1235
--------------
name --> pranitha
id --> 1236
--------------


In [ ]:
pb={
    'Transaction Type':[],
    'Transaction Amount':[],
    'Balance':[]
}

In [ ]:
pb['Transaction Type'].append('Withdraw')
pb['Transaction Amount'].append(10000)
pb['Balance'].append(16010)

In [ ]:
pb

{'Transaction Type': ['Withdraw', 'Withdraw'],
 'Transaction Amount': [10000, 10000],
 'Balance': [16010, 16010]}

Properties of set

*   no duplicate items


*   not indexed

*   mutable

*  Unordered



In [ ]:
s={1,2,3,4,1,2}


In [ ]:
a={1,2,3,4,5}
b={3,4,5,6,7}
i=a.intersection(b)
print(i)
u=a.union(b)
print(u)

{3, 4, 5}
{1, 2, 3, 4, 5, 6, 7}


In [ ]:
s.add('hello')
s.pop()

1

In [ ]:
s

{2, 3, 4, 'hello'}

In [ ]:
def marriage(bride,groom,place):
  print(f'come to {bride} and {groom}\'s marraige at {place}')

In [ ]:
marriage("nitya","srk","goa")

come to nitya and srk's marraige at goa


In [ ]:
pip install gradio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.6/50.6 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.7/56.7 MB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.8/319.8 kB 20.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.0/78.0 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.4/447.4 kB 26.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.5/144.5 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 87.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/1

In [ ]:
import gradio as gr

In [ ]:
def bye(name):
   return f'bye bye {name}'

In [ ]:
def add (a,b,op):
  return f'the addition is {a+b}'

In [ ]:
iface=gr.Interface(
    fn=add,
    inputs=[gr.Number(label='Enter a'), gr.Number(label='Enter b')],
    outputs='text',
    title='Addition Operation'
    )
iface.launch()

/usr/local/lib/python3.10/dist-packages/gradio/utils.py:980: UserWarning: Expected 3 arguments for function <function add at 0x7e741e4b71c0>, received 2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/gradio/utils.py:984: UserWarning: Expected at least 3 arguments for function <function add at 0x7e741e4b71c0>, received 2.
  warnings.warn(


Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://4768f092898b3a7733.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [ ]:
iface=gr.Interface(
    fn=bye,
    inputs='text',
    outputs='text',
    title='Bye Information'
)

Assessment Questions

In [ ]:
# CONDITIONAL STATEMENTS
# 1. Write a python program that checks if a number is positive,negative or zero.
num = int(input("Enter a number:"))
if num > 0:
  print("The Entered Number is Positive.")
elif num == 0:
  print("The Entered Number is Zero.")
else:
  print("Entered Number is Negative.")


Enter a number:5
The Entered Number is Positive.


In [ ]:
l=[4,6,1,3,9,2]
l.sort()
print("Sorted list:",l)
sum_elements = sum(l)
print("Sum of elements:", sum_elements)
l.append(5)
print("List after adding 5:", l)
l.remove(min(l))
print("List after removing the smallest element:",l)

Sorted list: [1, 2, 3, 4, 6, 9]
Sum of elements: 25
List after adding 5: [1, 2, 3, 4, 6, 9, 5]
List after removing the smallest element: [2, 3, 4, 6, 9, 5]


In [ ]:
responses = {}
while True:
   user_input = input("Enter something (type 'exit' to stop):")
   if user_input.lower() == "exit":
    break
   responses[user_input] = "Added to dictionary"
print("Goodbye")

Enter something (type 'exit' to stop):hello
Enter something (type 'exit' to stop):exit
Goodbye


In [ ]:
grades = {
    "Alice":85,
    "Bob":92,
    "Charlie":78,
    "Diana":88
}
def update_grade(student_name, new_grade):
  if student_name in grades:
    grades[student_name] = new_grade
    print(f"Updated {student_name}'s grade to{new_grade}.")
  else:
    print(f"Student {student_name} not found in the list.")
update_grade("Bob",95)
update_grade("Eve",80)


Updated Bob's grade to95.
Student Eve not found in the list.


In [ ]:
a= {1,2,3,4}
b={3,4,5,6}
intersection = a. intersection(b)
union = a.union(b)
print("Intersection:", intersection)
print("Union:", union)

Intersection: {3, 4}
Union: {1, 2, 3, 4, 5, 6}


In [ ]:
import math
def calculate_area(shape, dimensions):
  if shape.lower() =="circle":
    if len(dimensions) == 1:
      radius = dimensions[0]
      return math.pi * radius **2
    else:
      return "Error: Circle requires 1 dimension (radius)."
  elif shape.lower() =="rectangle":
      if len(dimensions) == 2:
        length, width = dimensions
        return length * width
      else:
        return "Error: Rectangle requires 2 dimension (length and width)."
  elif shape.lower() =="triangle":
      if len(dimensions) == 2:
        base, height = dimensions
        return base * height
      else:
        return "Error: Triangle requires 2 dimension (base and height)."
  else:
    return "Error : unsupported shape."
print (calculate_area("circle",[5]))
print (calculate_area("rectangle",[4,6]))
print (calculate_area("triangle",[3,7]))
print (calculate_area("hexagon",[2]))



78.53981633974483
24
21
Error : unsupported shape.


**Day 5**

In [ ]:
pip install gradio

In [ ]:
import gradio as gr

In [ ]:
def calc(a,b,op):
   if op== 'Addition':
    return f'the addition is{a+b}'
   elif op== 'Subtraction':
    return f'the Subtraction is{a-b}'
   elif op== 'Multiplication':
    return f'the Multiplication is{a*b}'
   elif op== 'Divison':
    return f'the Divison is{a/b}'



In [ ]:
calc(34,65,'Addition')

'the addition is99'

In [ ]:
iface=gr.Interface(
    fn=calc,
    inputs=[gr.Number(label='Enter a'),gr.Number(label='Enter b'),gr.Radio(choices=['Addition' ,'Subtraction', 'Multiplication','Division'])],
    outputs='text',
    title='Simple calculator',
    description='It calculates'
)

In [ ]:
iface.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://386e03af0237e14e5e.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [ ]:
def hotel (main,mq,juice,jq):
  bill=0
  if(main=='fried rice'):
    bill+=120*mq
  elif(main=='biryani'):
    bill+=150*mq
  elif(main=='roti'):
    bill+=70*mq
  if(juice=='orange'):
    bill+=40*jq
  elif(juice=='apple'):
    bill+=40*jq
  t=f'Your total bill is {bill}'
  v=gTTS(text=t,lang='en')
  v.save('bill.mp3')
  return bill,'bill.mp3'








In [ ]:
pip install gtts


In [ ]:
t='hello hitha, how are you'
v=gTTS(text=t,lang='fr',slow=True)
v.save('h.mp3')

In [ ]:
from gtts import gTTS

In [ ]:
def calc(a,b,op):
   if op== 'Addition':
    return f'the addition is{a+b}'
    v=gTTS(text=t,lang='en',)
    v.save('add.mp3')
   elif op== 'Subtraction':
    return f'the Subtraction is{a-b}'
    v=gTTS(text=t,lang='en',)
    v.save('sub.mp3')
   elif op== 'Multiplication':
    return f'the Multiplication is{a*b}'
    v=gTTS(text=t,lang='en',)
    v.save('mul.mp3')
   elif op== 'Divison':
    return f'the Divison is{a/b}'
    v=gTTS(text=t,lang='en',)
    v.save('div.mp3')

In [ ]:
iface=gr.Interface(
    fn=calc,
    inputs=[gr.Number(label='Enter a'),gr.Number(label='Enter b'),gr.Radio(choices=['Addition' ,'Subtraction', 'Multiplication','Division'])],
    outputs=[gr.Text(),gr.Audio()],
    title='Simple calculator',
    description='It calculates'
)

In [ ]:
iface.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://aadda5a8715b333050.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [ ]:
def hotel (main,mq,juice,jq):
  bill=0
  if(main=='fried rice'):
    bill+=120*mq
  elif(main=='biryani'):
    bill+=150*mq
  elif(main=='roti'):
    bill+=70*mq
  if(juice=='orange'):
    bill+=40*jq
  elif(juice=='apple'):
    bill+=40*jq
  t=f'Your total bill is {bill}'
  v=gTTS(text=t,lang='en')
  v.save('bill.mp3')
  return bill,'bill.mp3'


In [ ]:
iface=gr.Interface(
    fn=hotel,
    inputs=[gr.Radio(choices=['fried rice','biryani','roti']),gr.Number(label='Enter the main  Quantity'),gr.Radio(choices=['orange','apple']),gr.Number(label='Enter Juice Quantity')],
    outputs=[gr.Text(),gr.Audio()],
    title='Hotel Billing System'
)

In [ ]:
iface.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://a1d584b5e2924510e2.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


Libraries for Data Analytics


*  Pandas (data analytics & reading the data)
*   Numpy (numerical Python used for maths and stats in Data analytics)


*  Mathplotlib (used for ploting the graphs and charts)

*   seaborn (used for ploting the graphs and charts)
*   Plotly (used for ploting the dynamic graphs and charts)

  





In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4,5,5.6]
arr=np.array(l)
print(l)
print(arr)

[1, 2, 3, 4, 5, 5.6]
[1.  2.  3.  4.  5.  5.6]


homogenous,
ordered, indexed


In [ ]:
print(l*2)

[1, 2, 3, 4, 5, 5.6, 'hey', 1, 2, 3, 4, 5, 5.6, 'hey']


list is doubled

In [ ]:
print(arr*2)

[ 2.   4.   6.   8.  10.  11.2]


in numpy the elements get doubled

In [ ]:
arr=np.array([12,45,23,6,23,14,56])
arr

array([12, 45, 23,  6, 23, 14, 56])

In [ ]:
index=np.where(arr%2==0)

In [ ]:
arr[index]

array([12,  6, 14, 56])

In [ ]:
a=1 #scalar
b=[1,2,3,4,5]#vector
c=[[1,2,3],[4,5,6],[7,8,9]] #matrix


In [ ]:
cm=np.array(c)
cm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=np.array([1,21,312,42,56,6,7,8,9,10]).reshape((5,2))
a

array([[  1,  21],
       [312,  42],
       [ 56,   6],
       [  7,   8],
       [  9,  10]])

In [ ]:
sa=np.ravel(a)
sa

array([  1,  21, 312,  42,  56,   6,   7,   8,   9,  10])

In [ ]:
a=np.array([1,21,312,42,56,6,7,8,9,10]).reshape((5,2))
a.ndim

2

In [ ]:
sa=np.ravel(a)
sa.ndim

1

In [ ]:
cm=np.array(c)
cm.ndim

2

In [ ]:
type(sa)

numpy.ndarray

Pandas

2 types of datastructures

*  series
*   data frames

In [ ]:
import pandas as pd

In [ ]:
l=[1,2,3,4,5,'hey']
arr=np.array(l)
s=pd.Series(l,index=['a','b','c','d','e','f'])
df=pd.DataFrame(l,index=['a','b','c','d','e','f'],columns=['1st column'])
print('l->',l)
print('numpy arr->',arr)
print('Series ->')
print(s)
print('Data Frame->')
print(df)

l-> [1, 2, 3, 4, 5, 'hey']
numpy arr-> ['1' '2' '3' '4' '5' 'hey']
Series ->
a      1
b      2
c      3
d      4
e      5
f    hey
dtype: object
Data Frame->
  1st column
a          1
b          2
c          3
d          4
e          5
f        hey


In [ ]:
pb={
    'Transaction Type':[],
    'Transaction Amount':[],
    'Balance':[]
}

In [ ]:
pb['Transaction Type'].append('Withdraw')
pb['Transaction Amount'].append(10000)
pb['Balance'].append(16010)


In [ ]:
pbk=pd.DataFrame(pb)
pbk

Transaction Type  Transaction Amount  Balance
0         Withdraw               10000    16010